### ISSUE TITLE
barrier on classical bits 

### ISSUE THREAD

**Issue by DevelopDaily** [softwareQinc/staq#14]
This QASM can perfectly pass staq.

> OPENQASM 2.0;
> include "qelib1.inc";
> 
> qreg q[2];
> creg c[2];
> 
> barrier q, c;

I read the QASM spec again and it seems to be vague on the syntax. The grammar in Backus-Naur form allows that, but the spec also notes "Not all programs produced using this grammar are valid Open QASM circuits." All the examples in the spec suggest the barrier is designed for the qubits only.

If that syntax is indeed valid, what would be the purpose of a barrier on classical bits? I have exhausted my brainpower, but still cannot come up with a use case for that.

Could you please shed light on it?

Thank you.

**Comment by meamy** [comment]
I think the reality is that it's not explicitly illegal just because allowing it doesn't cause any run-time errors, and checking that all the bits used are qubits takes more work. That being said, I've thought about it and have a potential use case.

Since controls be can commuted through QASM measurements, a reasonable optimization might be to commute all measurements back through controls and measure qubits at the earliest possible point. In some situations this may be undesirable -- for instance when you want to keep the circuit "as unitary as possible" -- so the programmer can explicitly put a barrier on the classical bit to prevent the optimization. Of course this could be blocked by a barrier on the measured qubit as well, but conceptually I think a classical bit barrier could make sense in this situation.

**Comment by DevelopDaily** [comment]
Fair enough. Thanks.
