### ISSUE TITLE
A minor problem?

### ISSUE THREAD

**Issue by DevelopDaily** [softwareQinc/staq#33]
Here is a test file `input.qasm`:

```
OPENQASM 2.0;
include "qelib1.inc";

qreg q[2];

cu1(pi/4) q[0], q[1];
cu1(pi/4) q[0], q[1];
cu1(pi/4) q[0], q[1];
cu1(pi/4) q[0], q[1];
```

I run this:

`./staq   -S   -O3   -o   output.qasm   input.qasm`

The output will be:

```
OPENQASM 2.0;
include "qelib1.inc";

qreg q[2];
s q[1];
s q[0];
cx q[1],q[0];
rz((((-(pi/4)/2)+(-(pi/4)/2))+(-(pi/4)/2))+(-(pi/4)/2)) q[0];
cx q[1],q[0];
```

The argument of the `rz `gate does not look nice. Its length will grow with the number of the `cu1 `gates. It also happens on other gates. Would it be nice if the `staq `could evaluate the arguments of gates? Is it too difficult for the `staq `to achieve that? Any pros and cons?

By the way, the problem is considered minor because the argument expression is evaluated by the `qpp` correctly. When the `staq `API is used to traverse the circuit, it also correctly evaluates that to `rz(-1.57)`.

**Comment by meamy** [comment]
Agreed! The argument of the ```rz``` gate is definitely not ideal.

For the purposes of some optimizations in ```staq``` it's better to keep the arguments here symbolic rather than to outright evaluate them, but definitely it would be nice and possible to simplify these symbolic expressions. I'll put that on the to do list --- it's been something that we wanted to do for a long time anyway.

**Comment by 525125** [comment]
@DevelopDaily We've added parameter expression simplification
