### ISSUE TITLE
Bugs in benchmarks

### ISSUE THREAD

**Issue by khieta** [softwareQinc/staq#47]
I was running some tools on the benchmarks in [examples/staq_paper/benchmarks](https://github.com/softwareQinc/staq/tree/main/examples/staq_paper/benchmarks) and I noticed that two of the benchmarks are ill-formed, which causes most tools (including Staq) to fail. Possibly a bug when converting from their [original format](https://github.com/meamy/t-par/tree/master/Benchmarks) to QASM?
* mod_adder_1048576.qasm, [line 402](https://github.com/softwareQinc/staq/blob/main/examples/staq_paper/benchmarks/mod_adder_1048576.qasm#L402): `ccx qubits[48],qubits[29],qubits[48];`
* cycle_17_3.qasm, [line 9](https://github.com/softwareQinc/staq/blob/main/examples/staq_paper/benchmarks/cycle_17_3.qasm#L9): `ccx qubits[28],qubits[7],qubits[28];`

**Comment by meamy** [comment]
Thanks for pointing that out! It looks like it's actually a potential bug in the [original code](https://github.com/meamy/t-par/blob/2141d1b4669b4e40e38749e1e9d5901cfcfdf948/Benchmarks/cycle_17_3.qc#L18), which was itself auto-generated years ago from another format using a sed script, and hence likely error-prone. Ironically this isn't a problem in the .qc version which uses `ccz` gates instead.

I've fixed the benchmarks so that they don't cause errors anymore but are still semantically equivalent to the .qc versions (replacing `ccx` with `cx`, since `ccz` with two repeated arguments is quivalent to a `cz`. However, these benchmarks should all be re-written from scratch eventually. I'll make a separate issue for that.
